SRC = main.cpp phonebook.cpp contact.cpp

OBJ = ${SRC:.cpp=.o}

NAME = MyAwesomePhonebook

CC = c++

CFLAGS = -Wall -Werror -Wextra -std=c++98

RM = rm -rf

all : ${NAME}

${NAME} : ${OBJ}
		${CC} ${CFLAGS} ${OBJ} -o ${NAME}

clean : 
		${RM} ${OBJ}

fclean : clean
		${RM} ${NAME}
 
re : fclean all
